// Admin GEO: one task — assignment, place, dates, times, custom fields and proof — with edit,
// delete, and approve / reject for a staff-requested task.
// HRMSbackend GET / PUT / DELETE /api/admin/hrms-geo/task/:id.

import 'package:flutter/material.dart';

import '../../../config/app_colors.dart';
import '../../../services/admin_geo_service.dart';
import 'admin_geo_task_form_screen.dart';
import 'geo_admin_ui.dart';

class AdminGeoTaskDetailScreen extends StatefulWidget {
  const AdminGeoTaskDetailScreen({super.key, required this.taskId});

  /// Mongo id or task number (TSK-…).
  final String taskId;

  @override
  State<AdminGeoTaskDetailScreen> createState() => _AdminGeoTaskDetailScreenState();
}

class _AdminGeoTaskDetailScreenState extends State<AdminGeoTaskDetailScreen> {
  Map<String, dynamic>? _task;
  bool _loading = true;
  String? _error;
  bool _busy = false;
  bool _changed = false;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    setState(() => _error = null);
    try {
      final t = await AdminGeoService.instance.getTask(widget.taskId);
      if (!mounted) return;
      setState(() {
        _task = t;
        _loading = false;
      });
    } catch (e) {
      if (!mounted) return;
      setState(() {
        _error = e.toString();
        _loading = false;
      });
    }
  }

  String get _id => GeoUi.s(_task?['_id'], widget.taskId);

  Future<void> _run(Future<void> Function() action, String done, {bool close = false}) async {
    setState(() => _busy = true);
    try {
      await action();
      if (!mounted) return;
      GeoUi.ok(context, done);
      _changed = true;
      if (close) {
        Navigator.pop(context, true);
        return;
      }
      setState(() => _busy = false);
      await _load();
    } catch (e) {
      if (!mounted) return;
      setState(() => _busy = false);
      GeoUi.fail(context, e);
    }
  }

  Future<void> _approve() => _run(() => AdminGeoService.instance.updateTask(_id, {'status': 'Assigned'}), 'Task approved.');

  Future<void> _reject() async {
    if (!await GeoUi.confirm(context, 'Reject request', 'The requested task will be deleted.', action: 'Reject', destructive: true)) return;
    await _run(() => AdminGeoService.instance.deleteTask(_id), 'Task rejected.', close: true);
  }

  Future<void> _delete() async {
    if (!await GeoUi.confirm(context, 'Delete task', 'Delete "${GeoUi.s(_task?['title'], 'this task')}"? This cannot be undone.',
        action: 'Delete', destructive: true)) {
      return;
    }
    await _run(() => AdminGeoService.instance.deleteTask(_id), 'Task deleted.', close: true);
  }

  Future<void> _edit() async {
    final t = _task;
    if (t == null) return;
    final saved = await Navigator.of(context).push<bool>(MaterialPageRoute(
        builder: (_) => AdminGeoTaskFormScreen(taskType: GeoUi.s(t['type'], 'External'), task: t)));
    if (saved == true) {
      _changed = true;
      _load();
    }
  }

  @override
  Widget build(BuildContext context) {
    final t = _task;
    final auto = t?['autoGenerated'] == true;
    return PopScope(
      canPop: false,
      onPopInvokedWithResult: (didPop, _) {
        if (!didPop) Navigator.pop(context, _changed);
      },
      child: Scaffold(
        backgroundColor: GeoUi.bg,
        appBar: GeoUi.appBar('Task details', actions: [
          if (t != null && !auto) ...[
            IconButton(onPressed: _busy ? null : _edit, icon: const Icon(Icons.edit_outlined), tooltip: 'Edit'),
            IconButton(onPressed: _busy ? null : _delete, icon: const Icon(Icons.delete_outline_rounded), tooltip: 'Delete'),
          ],
        ]),
        body: _loading
            ? GeoUi.loading
            : RefreshIndicator(
                onRefresh: _load,
                child: _error != null ? GeoUi.error(_error!, _load) : _body(t!, auto),
              ),
      ),
    );
  }

  Widget _body(Map<String, dynamic> t, bool auto) {
    final status = GeoUi.s(t['status']);
    final custom = t['customFields'] is List
        ? [for (final f in t['customFields'] as List) if (f is Map) Map<String, dynamic>.from(f)]
        : <Map<String, dynamic>>[];
    final proof = GeoUi.s(t['proofImg']);
    final internal = t['type'] == 'Internal';
    return ListView(
      padding: const EdgeInsets.fromLTRB(16, 16, 16, 32),
      children: [
        GeoUi.card(
          child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
            Row(children: [
              Expanded(child: Text(GeoUi.s(t['title'], 'Task'), style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w700, color: GeoUi.ink))),
              const SizedBox(width: 8),
              GeoUi.statusPill(status),
            ]),
            const SizedBox(height: 4),
            Text('${GeoUi.s(t['id'])} · ${GeoUi.s(t['type'])}', style: const TextStyle(color: GeoUi.muted, fontSize: 12.5)),
            if (auto)
              const Padding(
                padding: EdgeInsets.only(top: 8),
                child: Text('System-generated branch visit: it cannot be edited or deleted here. Remove the branch under Employee Access to stop it.',
                    style: TextStyle(fontSize: 12.5, color: GeoUi.muted)),
              ),
            const SizedBox(height: 12),
            const Divider(height: 1),
            const SizedBox(height: 8),
            GeoUi.kv('Description', GeoUi.s(t['description'])),
            GeoUi.kv('Staff', '${GeoUi.s(t['staffName'])} ${GeoUi.s(t['staffId']).isNotEmpty ? '(${GeoUi.s(t['staffId'])})' : ''}'.trim()),
            if (internal) GeoUi.kv('Branch', GeoUi.s(t['branch'])) else GeoUi.kv('Customer', GeoUi.s(t['customerName'])),
            if (!internal) GeoUi.kv('Address', GeoUi.s(t['customerAddress'])),
            if (!internal && t['latitude'] is num)
              GeoUi.kv('Geofence', '${t['latitude']}, ${t['longitude']} · ${GeoUi.n(t['radius'])} m'),
            GeoUi.kv('Assigned by', GeoUi.s(t['assignedBy'])),
            GeoUi.kv('Assigned on', GeoUi.date(t['assignedDate'])),
            GeoUi.kv('Start date', GeoUi.date(t['startDate'])),
            GeoUi.kv('End date', GeoUi.date(t['endDate'])),
            if (GeoUi.s(t['completedDate']).isNotEmpty) GeoUi.kv('Completed', GeoUi.date(t['completedDate'])),
            GeoUi.kv('Time in', GeoUi.s(t['timeIn'])),
            GeoUi.kv('Field in', GeoUi.s(t['actualFieldInTime'])),
            GeoUi.kv('Time out', GeoUi.s(t['timeOut'])),
          ]),
        ),
        if (custom.isNotEmpty)
          GeoUi.card(
            child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
              GeoUi.sectionTitle('Additional details'),
              for (final f in custom) GeoUi.kv(GeoUi.s(f['label']), GeoUi.s(f['value'])),
            ]),
          ),
        if (proof.startsWith('http'))
          GeoUi.card(
            child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [
              GeoUi.sectionTitle('Proof'),
              ClipRRect(
                borderRadius: BorderRadius.circular(12),
                child: Image.network(proof, fit: BoxFit.cover,
                    errorBuilder: (_, _, _) => const Text('Proof image could not be loaded.', style: TextStyle(fontSize: 13, color: GeoUi.muted))),
              ),
            ]),
          ),
        if (status == 'Requested') ...[
          const SizedBox(height: 8),
          GeoUi.primaryButton('Approve request', _approve, busy: _busy),
          const SizedBox(height: 12),
          SizedBox(
            width: double.infinity,
            height: 48,
            child: OutlinedButton.icon(
              onPressed: _busy ? null : _reject,
              style: OutlinedButton.styleFrom(side: const BorderSide(color: AppColors.error, width: 1.2)),
              icon: const Icon(Icons.close_rounded, color: AppColors.error),
              label: const Text('Reject request', style: TextStyle(color: AppColors.error)),
            ),
          ),
        ],
      ],
    );
  }
}
